# -*- coding: utf-8 -*-
"""ricardo_tp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BDEYeLNwLs0SKzNHv8wgTnBjEAHO0Paq
"""

#Exercício 1
texto = "Sítio do pica-pau amarelo \n 2023"

caracteres = [c for c in texto if c != ' ' and c != '\n']

print(caracteres)

#Exercício 2
def ordenar_cartas(cartas):
    n = len(cartas)

    for i in range(1, n):

        carta_atual = cartas[i]
        j = i - 1

        while j >= 0 and cartas[j] > carta_atual:
            cartas[j + 1] = cartas[j]
            j -= 1

        cartas[j + 1] = carta_atual

    return cartas


cartas = [7, 3, 10, 1, 13, 5, 2, 12, 8, 6, 11, 4, 9]
print("Antes:", cartas)
ordenado = ordenar_cartas(cartas)
print("Depois:", ordenado)

#Exercício 5
def greatestNumber(array):
    if not array:
        return None

    maior = array[0]

    i = 1
    while i < len(array):

        if array[i] > maior:
            maior = array[i]
        i += 1

    return maior


array = [3, 5, 2, 9, 4]
print(greatestNumber(array))

#Exercício 6
def square_for_rice(grains):
    square = 1
    current_grains = 1

    while current_grains < grains:
        current_grains *= 2
        square += 1

    return square

grains = int(input("Digite a quantidade de grãos: "))
print(square_for_rice(grains))

#Exercício 8
def bubble_sort_left_right(lista):
    n = len(lista)

    left = 0
    right = n - 1

    while left < right:

        for j in range(left, right):
            if lista[j] > lista[j + 1]:
                lista[j], lista[j + 1] = lista[j + 1], lista[j]

        right -= 1

        for j in range(right, left, -1):
            if lista[j] < lista[j - 1]:
                lista[j], lista[j - 1] = lista[j - 1], lista[j]

        left += 1
lista = [64, 34, 33, 12, 14, 13, 65, 38, 2]

bubble_sort_left_right(lista)
print(lista)

#Exercício 9
def bubble_sort_(lista):
    n = len(lista)
    for i in range(n):
        for j in range(0, n - i - 1):
            if lista[j] > lista[j + 1]:
                lista[j], lista[j + 1] = lista[j + 1], lista[j]

print('Lista 1')
lista = [64, 34, 25, 12, 22, 11, 90, 18, 8, 9]
bubble_sort_(lista)
print(lista)
print('\n')
#

print('Lista 2')
lista = [64, 34, 33, 12, 14, 13, 65, 38, 2]
bubble_sort_(lista)
print(lista)

#Exercício 10

def bubble_sort_string(lista):
    n = len(lista)

    for i in range(n):
        for j in range(0, n - i - 1):
            if lista[j] > lista[j + 1]:
                lista[j], lista[j + 1] = lista[j + 1], lista[j]

lista = ["mochila", "caneta", "caderno", "tablet"]
bubble_sort_string(lista)
print(lista)